# Generated by Django 6.0.2 on 2026-04-11 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='stripe_customer_id',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='stripe_subscription_id',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='stripe_price_id',
        ),
    ]
