# Generated by Django 6.0.2 on 2026-06-01 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_remove_membership_stripe_customer_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='cancel_at_period_end',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='membership',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='membership',
            name='stripe_price_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='membership',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='stripe_price_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
